version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: my_vue_app_nginx
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: my_vue_app_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - nginx